### ISSUE TITLE
Problems on macos: failed to create path for auto-compiled file 

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sph-sc#1]
Hi,
I try (again) to install or at least run sph-sc on mac. It doesn't work. For one I could no install sph-lib with the script, so copied sph-lib manually into a load path. I'm not sure if I did it successfully, but what seems to work it importing sph-libs on the repl. 
Now with sph-sc the "problems" begin with the exe/install script. My mac doesnt like some of the 'cp' commands options, and then the install script tried to install the modules in read only directory. 
So in the end, I manually copied the sph/lang into the load path. But still exe/sc is still not running, and while try to debug the problem, I comment out almost all of the 'sc' comment, so it looks like this

```
#!/usr/bin/env guile
!#
(use-modules (sph) (sph lang indent-syntax))
;  (sph lang scheme) (sph string)
```
this happens when I run it
```

/sc.bin
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /Users/ben/[...]/sph-lib/sph-sc/exe/./sc.bin
;;; WARNING: compilation of /Users/ben/[...]/sph-lib/sph-sc/exe/./sc.bin failed:
;;; failed to create path for auto-compiled file "/Users/ben/[...]sph-lib/sph-sc/exe/./sc
```

**Comment by jkalbhenn** [comment]
hi and thanks for bringing this up,

it is unforturnate that the installer does not work, i should revise the install process. i wasnt able to test on mac.
"failed to create path" is an unusual error. i will try to explain the full manual install process in detail. i have since also fixed a compile error in the code.

the version of guile should ideally be 3 or above. this can be checked with `guile -v`. guile 2 gives an error about a new #:declarative? keyword and would need a workaround.

**the installation of sph-lib**
* download or clone the [sph-lib](https://github.com/sph-mn/sph-lib) repository
* copy or symlink everything from under `modules/` to a path listed when executing `guile -c '(display %load-path)'`. an example of that process would be `cp -rt /usr/share/guile/site modules/*`, where `/usr/share/guile/site` is a guile load path. in the end, the directory `/usr/share/guile/site/sph` exists
* run `./exe/test`. if that runs through and lists tested features with numbers, sph-lib should be fully installed

**the installation of sph-sc**
* download or clone the [sph-sc](https://github.com/sph-mn/sph-sc) repository
* same as sph-lib: copy or symlink everything from under `modules/` to a path listed when executing `guile -c '(display %load-path)'`. for example, after copying, the file `/usr/share/guile/site/sph/lang/sc.scm` exists
* run `./exe/test` to test if all modules are installed and working
* copy or symlink `exe/sc` to a directory listed when executing `echo $PATH`. ensure that the execute bit is set on the installed file, `chmod +x targetpath` can set it, `ls -l targetpath` should include an x in the permissions, like rwx
* the command `sc` should now be available on the command line, for example `sc --help`

**Comment by bentxt** [comment]
Thanks, for the great answer and manual. I tried this and it still fails with some new errors

First Some notes: 

my guile:
```
guile -v
guile (GNU Guile) 3.0.4
```

Suggestion:
Instead of hardcoding guile, use env in the shebang
```
# works not on mac  #!/usr/bin/guile
 #!/usr/bin/env guile
```

The script in exe/test of sph-lib gave me alot of thes warnings/errors in the form of
```
;;; WARNING: compilation of /Users/ben/...sph-sc/sph-lib/modules/test/module/sph/tree.scm failed:
161 
;;; failed to create path for auto-compiled file "/Users/...sph-sc/sph-lib/modules/test/module/sph/tree.scm"
```
This make not much sense to me

Then at the he end of the test output of sph-lib looks like this, which indicates it was installed successfully (I guess?)
```
test module sph filesystem
  set-up-filesystem-glob 1
  filesystem-glob 1 2 3 4 5 6 7
  directory-tree 1
  directory-tree-leaf-directories 1
  directory-prefix-tree 1
  path->full-path 1 2
  set-up-realpath* 1
  realpath*
    failure
    i: (equal? realpath-temp-path (realpath* (realpath-temp-path* "c/d")))
    e: #t
    o: #f
```

Well, at least, this file exists 
`/usr/local/Cellar/guile/3.0.4/share/guile/site/3.0/sph/cli.scm`

Which seems to be one of the load-path
```
guile -c '(display %load-path)'
(/usr/local/Cellar/guile/3.0.4/share/guile/3.0 /usr/local/Cellar/guile/3.0.4/share/guile/site/3.0 /usr/local/Cellar/guile/3.0.4/share/guile/site /usr/local/Cellar/guile/3.0.4/share/guile)⏎
```

Same with the sph-sc lib, which I've installed manually like you described. The modules seem to be in the right place, but my system still has issues

```
sc example.sc
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /Users/ben/builds/sph-sc/sph-sc/exe/sc
;;; WARNING: compilation of /Users/ben/builds/sph-sc/sph-sc/exe/sc failed:
;;; In procedure mkstemp!: Permission denied
ice-9/psyntax.scm:2800:12: In procedure syntax-violation:
Syntax error:
unknown location: ...: bad use of '...' syntactic keyword in subform ... of ..
```

I think the problem comes from list-q in
`68         (list-q ((source-path ... target-path)) ((source-path))`

**Comment by sph-mn** [comment]
this is actually something that was just fixed today:
> (list-q ((source-path ... target-path)) ((source-path))

the current version should not have this problem.

> ;;; failed to create path for auto-compiled file "/Users/...sph-sc/sph-lib/modules/test/module/sph/tree.scm"
> mkstemp!: Permission denied

these both look like missing filesystem permissions instead of errors in the code. these are not errors i have usually seen with guile. guile creates compiled files in its cache directory (.cache/guile in my case, which can also be freely removed). maybe test if you can create the listed path manually. guile might be proceeding without a compiled file, but will have to recompile each time.

i am not sure where macos installs binaries, but maybe for now it is possible to create a symlink to guile at /usr/bin/guile to not have to rewrite to /usr/bin/env. until it is changed in the code.

**Comment by bentxt** [comment]
Thanks for the fix, It works now :-)

I also think that the permission errors, have nothing to do with sph-sc. In fact now that I think about it, its a constant annoyance with guile, at least on mac. Guile is the only system I have this problems, which is the reason I prefer Gauche Scheme.
