### ISSUE TITLE
Problem with ./exe/install on macos

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sph-sc#3]
Hi there,
Sadly the install script fails run on my machine, due an error with the `cp` command.

```
sudo exe/install
Password:
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

```

This is comming from Guile I guess, but still maybe there is a workaround for sph-sc ...

Ben

**Comment by sph-mn** [comment]
hi, the install script only works on gnu/linux for now. can you run the installation "without the installer" mentioned in the readme here https://github.com/sph-mn/sph-sc#without-the-installer ?

the cp utilities are unfortunately very different between gnu and bsd style systems, the installer should not need it anyway but i havent fixed that yet.

**Comment by sph-mn** [comment]
to address the issues with the installer, i have rewritten it so that it can work on any system. the default installation paths might still be incorrect for a given system (executables into /usr/bin, libraries into /usr/lib, etc), but they can be overridden with command-line options. to use the new version of the installer, the new version of sph-lib and sph-sc is needed.

**Comment by tsequitur** [comment]
closed because of inactivity.

**Comment by sph-mn** [comment]
closed because of inactivity.
